<?php if(!isset($user)): ?>
<form action="/session" method="post">
  <div>
    <label>
        Имя : 
      <input type="text" name="user[name] value="">
    </label>
  </div>
    <input type="submit" value="Sign In">
</form> 
<?php else: ?>
<form action="/session" method="post">
  <div>
        <?= $user['name'] ?>
  </div>
  <input type="hidden" name="_METHOD" value="delete">
    <input type="submit" value="Sign Out">
</form>
<?php endif ?>